-
  sheet_header: ID
  column_name: id_on_sheet
-
  sheet_header: 別ツイ
  column_name: other_tweet_ids_text
-
  sheet_header: ツイ見られない？
  column_name: is_invisible
-
  sheet_header: 集計対象外？
  column_name: is_out_of_counting
-
  sheet_header: 内容
  column_name: contents
-
  sheet_header: 備考
  column_name: memo
-
  sheet_header: キャラ1
  column_name: character_01
-
  sheet_header: キャラ2
  column_name: character_02
-
  sheet_header: キャラ3
  column_name: character_03
