-
  sheet_header: キャラ（集計）
  column_name: character_name_for_sheet_totalling
-
  sheet_header: 応募数 # Integer
  column_name: number_of_applications
-
  sheet_header: 応募状況用
  column_name: character_name_for_public
