# check_words の中身を連続で見ていった際に、これらの語の場合はキャラ名サーチをしない
# ここでは、「check_wordsに現れている語の中で除外する語」を指定する
# そもそも check_words に含まれていない語はここではどうしようもない
words:
  - 'ノ'
  - 'さん'
  - 'てる'
  - '方'
  - 'い'
  - 'せ'
  - 'ん'
  - '回'
  - '率'
  - '%'
  - 'お'
  - '金'
  - '力'
  - ':/'
  - 'BC'
  - 'vr'
  - '100%'
  - 'BCd'
  - 'vr'
  - 'a'
  - 'b'
  - 'c'
  - 'd'
  - 'e'
  - 'f'
  - 'g'
  - 'h'
  - 'i'
  - 'j'
  - 'k'
  - 'l'
  - 'm'
  - 'n'
  - 'o'
  - 'p'
  - 'q'
  - 'r'
  - 's'
  - 't'
  - 'u'
  - 'v'
  - 'w'
  - 'x'
  - 'y'
  - 'z'
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
  - 'T'
  - 'U'
  - 'V'
  - 'W'
  - 'X'
  - 'Y'
  - 'Z'
  - "cE"
  - "Dp"
  - 'ほら'
  - '次'
  - '砦'
  - 'する'
  - '心'
  - 'なっ'
  - 'たら'
  - 'おれ'
  - 'だ'
  - 'さま'
  - 'u'
  - '英'
  - '語'
  - '版'
  - 'だ'
  - 'いう'
  - 'い'
  - '∶'
  - '/cI'
  - 'u'
  - ':/'
  - 'me'
  - 'at'
  - '船'
  - '者'
  - 'い'
  - 'さま'
  - '子'
  - 'お'
  - '題'
  - '話'
  - 'だ'
  - '枚'
  - 'ます'
  - 't'
  - 'なっ'
  - 'た'
  - '時'
  - '元'
  - '軍'
  - 'いる'
  - '話'
  - 'だ'
  - '題'
  - 'する'
  - '時'
  - 'なぁ'
  - 'まし'
  - 'た'
  - 'ます'
  - 'お'
  - ':/'
  - 'z'
  - '63z'
  - 'さ'
  - 'せ'
  - 'たい'
  - '話'
  - 'OT'
  - 'y'
  - '事'
  - '軍'
  - '料'
  - '理'
  - '長'
  - '小'
  - '人'
  - '公'
  - '人公'
  - '様'
  - '票'
  - '/'
  - 'm'
  - '('
  - ')'
  - '_'
  - '__'
  - '一'
  - 'な'
  - 'る'
  - 'なる'
  - '王'
  - '異'
  - '世'
  - '界'
  - '世界'
  - 'ち'
  - 'ゃ'
  - 'ん'
  - 'な'
  - 'る'
  - 'が'
  - 'れ'
  - 'し'
  - '百'
  - '年'
  - 'の'
  - '時'
  - 'い'
  - '（'
  - '）'
  - '幻'
  - '水'
  - '総'
  - '選'
  - '挙'
  - '選挙'
  - '幻水'
  - 'バー'
  - 'ッ'
