on_database_character_name_to_on_sheet_character_name:
  アルシュタート・ファレナス: アルシュタート
  アルベルト・シルバーバーグ: アルベルト
  イリア・バルカイ: イリア
  オデッサ・シルバーバーグ: オデッサ
  カーン・マリィ: カーン
  キルキス・シャナ・クエス・ラビアンカーナ: キルキス
  クラウス・ウィンダミア: クラウス
  クリス・ライトフェロー: クリス
  ゲオルグ・プライム: ゲオルグ
  サイアリーズ・ファレナス: サイアリーズ
  ザジ・キュイロス: ザジ
  サロメ・ハラス: サロメ
  シーザー・シルバーバーグ: シーザー
  シエラ・ミケーネ: シエラ
  ジョウイ・アトレイド（ブライト）: ジョウイ
  ジル・ブライト: ジル
  スノウ・フィンガーフート: スノウ
  ソロン・ジー: ソロン
  ティアクライス主人公（団長）: TK主人公
  ナッシュ・ラトキエ（クロービス）: ナッシュ
  パーシヴァル・フロイライン: パーシヴァル
  フリード・Ｙ: フリード・Y
  フレッド・マクシミリアン: フレッド
  ペック（暗器使い）: ペック
  ベルナデット・イーガン: ベルナデット
  ボルス・レッドラム: ボルス
  マッシュ・シルバーバーグ: マッシュ
  ユーラム・バロウズ: ユーラム
  ヨシュア・レーベンハイト: ヨシュア
  リウ・シエン: リウ
  リムスレーア・ファレナス: リムスレーア
  ルイス・キファーソン: ルイス
  ルカ・ブライト: ルカ
  ルセリナ・バロウズ: ルセリナ
  ワイアット・ライトフェロー（ジンバ）: ジンバ
  幻水1主人公（坊ちゃん）:
    - 1主人公
    - 坊ちゃん
  幻水2主人公（2主）: 2主人公
  幻水4主人公（4様）: 4主人公
  幻水5主人公（王子）: 5主人公
