on_database_character_name_to_on_sheet_character_name:
  シーザー・シルバーバーグ: シーザー
  アルベルト・シルバーバーグ: アルベルト
  ワイアット・ライトフェロー（ジンバ）: ジンバ
  ジョウイ・アトレイド（ブライト）: ジョウイ
  ジル・ブライト: ジル
  リムスレーア・ファレナス: リムスレーア
  幻水1主人公（坊ちゃん）: 1主人公
  イリア・バルカイ: イリア
  ルセリナ・バロウズ: ルセリナ
  シエラ・ミケーネ: シエラ
  フレッド・マクシミリアン: フレッド
  幻水4主人公（4様）: 4主人公
  ルカ・ブライト: ルカ
  フリード・Ｙ: フリード・Y
  ゲオルグ・プライム: ゲオルグ
  ナッシュ・ラトキエ（クロービス）: ナッシュ
  幻水5主人公（王子）: 5主人公
  アルシュタート・ファレナス: アルシュタート
  クリス・ライトフェロー: クリス
  ザジ・キュイロス: ザジ
  幻水2主人公（2主）: 2主人公
  ソロン・ジー: ソロン
  ペック（暗器使い）: ペック
  ボルス・レッドラム: ボルス
  サロメ・ハラス: サロメ
  パーシヴァル・フロイライン: パーシヴァル
  ルイス・キファーソン: ルイス
  クラウス・ウィンダミア: クラウス
  ティアクライス主人公（団長）: TK主人公
  カーン・マリィ: カーン
  ヨシュア・レーベンハイト: ヨシュア
  ユーラム・バロウズ: ユーラム
  サイアリーズ・ファレナス: サイアリーズ
  オデッサ・シルバーバーグ: オデッサ
  リウ・シエン: リウ
  スノウ・フィンガーフート: スノウ
  キルキス・シャナ・クエス・ラビアンカーナ: キルキス
