default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || Rails.application.credentials[:rails_max_threads] || 5 %>

production:
  <<: *default
  database: suikoden_election_2022_production
  host: <%= ENV['POSTGRES_HOST_PRODUCTION'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_PRODUCTION'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_PRODUCTION'] %>
  password: <%= ENV['POSTGRES_PASSWORD_PRODUCTION'] %>

development:
  <<: *default
  database: suikoden_election_2022_development
  host: <%= ENV['POSTGRES_HOST_DEVELOPMENT'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_DEVELOPMENT'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_DEVELOPMENT'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD_DEVELOPMENT'] || 'postgres' %>

test:
  <<: *default
  # url: <%= ENV['DATABASE_URL'].presence %>
  database: suikoden_election_2022_test
  host: <%= ENV['POSTGRES_HOST_TEST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_TEST'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME_TEST'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD_TEST'] || 'postgres' %>

# 外部のデータベース
tweet_storage:
  <<: *default
  database: <%= ENV['TWEET_STORAGE_DATABASE'] %>
  host: <%= ENV['TWEET_STORAGE_HOST'] %>
  port: <%= ENV['TWEET_STORAGE_PORT'] %>
  username: <%= ENV['TWEET_STORAGE_USERNAME'] %>
  password: <%= ENV['TWEET_STORAGE_PASSWORD'] %>
