name: Cloud Run に production デプロイする

on:
  workflow_run:
    workflows:
      - '幻水総選挙2022 バックエンド（サービスpg）'
    types:
      - completed

env:
  # TODO: Git のタグを取得して、イメージのタグにする
  DOCKER_IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.CLOUD_RUN_PROJECT }}/cloud-run-source-deploy/gensosenkyo-2022-backend
  GCP_REGION: ${{ secrets.CLOUD_RUN_REGION }}
  GCP_AUTH_HOST: asia-northeast1-docker.pkg.dev
  CLOUD_RUN_SERVICE_NAME: gensosenkyo-2022-backend

jobs:
  on-success:
    if: ${{ github.ref_name == 'main' }}
    # name: Cloud Run に production デプロイする
    runs-on: ubuntu-latest
    steps:
      - name: ソースコードをチェックアウトする
        uses: actions/checkout@v3
      - name: GCP の認証を行う
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: GCP の CLI の認証を行う
        run: |
          gcloud auth configure-docker ${{ env.GCP_AUTH_HOST }}
      - name: Docker イメージ をビルドする
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
      - name: Docker イメージ をプッシュする
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
          image: ${{ env.DOCKER_IMAGE }}
          region: ${{ env.GCP_REGION }}
