name: 幻水総選挙2022 バックエンド

on:
  push:
  workflow_dispatch:

jobs:
  gss2022_backend:
    name: （PG services版）継続的インテグレーション
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
        ruby-version: ["3.1"]
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          # POSTGRES_DB: suikoden_election_2022_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: （予定地）Node.js のセットアップを行う
      run: |
        echo 'Node.js を使うことがあれば "actions/setup-node" を用いる'
      # uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: "yarn"
    - name: db:create db:migrate する
      run: |
        bin/rails db:create db:migrate
      env:
        # POSTGRES_HOST: localhost
        # POSTGRES_PORT: 5432
        POSTGRES_USERNAME_TEST: username
        POSTGRES_PASSWORD_TEST: password
    - name: DB接続確認
      run: |
        bundle exec rails runner "puts Asset.new"
      # env:
        # POSTGRES_HOST_TEST: postgres #=> 接続失敗する
        # POSTGRES_HOST: localhost
        # POSTGRES_PORT: 5432
        # POSTGRES_USERNAME_TEST: postgres
        # POSTGRES_PASSWORD_TEST: postgres
    - name: RSpec を実行する
      run: |
        bundle exec rspec
      # env:
        # POSTGRES_HOST: localhost
        # POSTGRES_PORT: 5432
        # POSTGRES_HOST: localhost
        # POSTGRES_HOST: postgres
        # POSTGRES_PORT: 5432
        # POSTGRES_HOST_TEST: postgres
        # POSTGRES_HOST_TEST: localhost
        # POSTGRES_PORT_TEST: 5432
        # POSTGRES_USERNAME_TEST: postgres
        # POSTGRES_PASSWORD_TEST: postgres

        # const pgclient = new Client({
        #     host: process.env.POSTGRES_HOST,
        #     port: process.env.POSTGRES_PORT,
        #     user: 'postgres',
        #     password: 'postgres',
        #     database: 'postgres'
        # });
        # https://docs.github.com/ja/enterprise-server@3.1/actions/using-containerized-services/creating-postgresql-service-containers