name: 幻水総選挙2022 バックエンド

on:
  push:
  workflow_dispatch:

jobs:
  gss2022_backend:
    name: 継続的インテグレーション
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
        ruby-version: ["3.1"]
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: suikoden_election_2022_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      POSTGRES_HOST_TEST: 127.0.0.1
      POSTGRES_PORT_TEST: 5432
      POSTGRES_USERNAME_TEST: postgres
      POSTGRES_PASSWORD_TEST: postgres
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: （予定地）Node.js のセットアップを行う
      run: |
        echo 'Node.js を使うことがあれば "actions/setup-node" を用いる'
      # uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: "yarn"
    - name: db:create db:migrate する
      run: |
        bin/rails db:create db:migrate
    - name: RSpec を実行する
      run: |
        bundle exec rspec
