name: 幻水総選挙2022 バックエンド（サービスpg）

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  gss2022_backend:
    name: (pg on services) 継続的インテグレーション
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
        ruby-version: ["3.1"]
    services:
      postgres:
        image: postgres:15.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      CI: true
      RAILS_ENV: test
      PG_HOST_TEST: localhost
      PG_PORT_TEST: 5432
      PG_USERNAME_TEST: postgres_user
      PG_PASSWORD_TEST: postgres_password
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: $ bundle install を行う
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: データベースをセットアップする
      run: |
        bin/rails db:prepare
    - name: RSpec を実行する
      run: |
        bundle exec rspec
