name: 幻水総選挙2022 バックエンド

on:
  push:
  workflow_dispatch:

jobs:
  gss2022_backend:
    name: （PG services版）継続的インテグレーション
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
        ruby-version: ["3.1"]
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          # POSTGRES_DB: suikoden_election_2022_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: （予定地）Node.js のセットアップを行う
      run: |
        echo 'Node.js を使うことがあれば "actions/setup-node" を用いる'
      # uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: "yarn"
    - name: db:create db:schema:load db:migrate する (db:setup)
      run: |
        bin/rails db:setup
      env:
        # POSTGRES_HOST: localhost
        # POSTGRES_PORT: 5432
        RAILS_ENV: test
        POSTGRES_USERNAME_TEST: username
        POSTGRES_PASSWORD_TEST: password
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   if: ${{ github.ref_name == 'feat/add_github-actions_on_services-pg' }}
    #   timeout-minutes: 15
    #   with:
    #     sudo: true
    #     limit-access-to-actor: true
    - name: DB接続確認
      run: |
        bundle exec rails runner "puts Asset.new"
        bundle exec rspec
      env:
        RAILS_ENV: test
        POSTGRES_USERNAME_TEST: username
        POSTGRES_PASSWORD_TEST: password
        # POSTGRES_HOST_TEST: postgres #=> 接続失敗する
        # POSTGRES_HOST: localhost
        # POSTGRES_PORT: 5432
        # POSTGRES_USERNAME_TEST: postgres
        # POSTGRES_PASSWORD_TEST: postgres
    - name: Wait for PostgreSQL to be ready
      run: |
        until : > /dev/tcp/localhost/5432; do
          echo -n .
          sleep 1
        done

        echo Success
    - name: RSpec を実行する
      run: |
        RAILS_ENV=test POSTGRES_USERNAME_TEST=username POSTGRES_PASSWORD_TEST=password bundle exec rspec spec/models/user_spec.rb
      env:
        # RAILS_ENV: test
        # POSTGRES_HOST_TEST: 127.0.0.1
        POSTGRES_USERNAME_TEST: username
        POSTGRES_PASSWORD_TEST: password
        # POSTGRES_HOST: localhost
        # POSTGRES_PORT: 5432
        # POSTGRES_HOST: localhost
        # POSTGRES_HOST: postgres
        # POSTGRES_PORT: 5432
        # POSTGRES_HOST_TEST: postgres
        # POSTGRES_HOST_TEST: localhost
        # POSTGRES_PORT_TEST: 5432
        # POSTGRES_USERNAME_TEST: postgres
        # POSTGRES_PASSWORD_TEST: postgres

        # const pgclient = new Client({
        #     host: process.env.POSTGRES_HOST,
        #     port: process.env.POSTGRES_PORT,
        #     user: 'postgres',
        #     password: 'postgres',
        #     database: 'postgres'
        # });
        # https://docs.github.com/ja/enterprise-server@3.1/actions/using-containerized-services/creating-postgresql-service-containers